name: CI for Hangman Game


on:
  push:
   branches: ["main"]
   #paths:
      #- HangmanMSDocker/**
  pull_request:
   branches: ["main"]
  workflow_dispatch: 
  
  
jobs:
  buildMultistage:
       runs-on: ubuntu-latest
       env:
         WORKING_DIR: HangmanMSDocker
       steps:
       - name: checkout git repo
         uses: actions/checkout@v3
         
       - name: login to docker
         uses: docker/login-action@v2
         with:
          username: ${{ secrets.docker_name_user }}
          password: ${{ secrets.DOCKERHUB }}
         
       #- name: build docker image
         #run:  docker build -t 10402033/hangmanmultistage:latest ${{ env.WORKING_DIR }}
       
       - name: Set up QEMU
         uses: docker/setup-buildx-action@v2
       
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
         
       - name: Build and push
         uses: docker/build-push-action@v4
         with:
          context: ${{ env.WORKING_DIR }}
          push: true
          tags: 10402033/hangmanmultistage:v2
    
        
   

   
  
     
 
   
