name: CI for Hangman Game


on:
  push:
   branches: ["main"]
   #paths:
      #- HangmanMSDocker/**
  pull_request:
   branches: ["main"]
  workflow_dispatch: 
  
  
jobs:
  buildMultistage:
       runs-on: ubuntu-latest
       env:
         WORKING_DIR: HangmanMSDocker
       steps:
       - name: checkout git repo
         uses: actions/checkout@v3
       - name: build docker image
         run:  docker build -t 10402033/hangmanmultistage:latest ${{ env.WORKING_DIR }}
         
       
       - name: tag and push the built image to Docker hub
         uses: docker/build-push-action@v4
         with: 
          push: true
          tags: user/app:latest
   
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v2
         with:
             name: .net-app
             path: HangmanApp

  
     
 
   
