name: CI for Hangman Game


on:
  push:
   branches: ["main"]
   paths:
      - HangmanMSDocker/**
  pull_request:
   branches: ["main"]
  workflow_dispatch: 
  
  
jobs:
  buildMultistage:
       runs-on: ubuntu-latest
       env:
         WORKING_DIR: HangmanMSDocker
       steps:
       - name: checkout git repo
         uses: actions/checkout@v3
       - name: build docker image
         run:  docker build -t HangmanMultiStage:multi .
         
       - name: docker login
         uses: docker/login-action@v1
         with:
            registry: https://hub.docker.com/u/10402033
            username: ${{ secrets['10402033'] }}
            password: ${{ secrets.dckr_pat_aRrWp81RoGvGDWCvoCSMWlyCJpc }}
       - name: tag and push the built image to Docker hub
         run: |
            docker tag 10402033/HangmanMultiStage 10402033/HangmanMultiStage:multi
            docker push 10402033/HangmanMultiStage:multi
         env:
           tag: multi
   
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v2
         with:
             name: .net-app
             path: HangmanApp

  
     
 
   
