name: Starter Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello,world"
      - name: checkout repo
        uses: actions/checkout@v3.5.2
      - name: List contents
        run: ls
    
  
