
name: Continuous integration for template APi

on:
  push:
   branches: ["main"]
   #paths:
      #- TemplateApi/**
  pull_request:
   branches: ["main"]
  workflow_dispatch: 
  
  
jobs:
  TemplateApiMulti:
       runs-on: ubuntu-latest
       env:
         WORKING_DIR: TemplateApi
       steps:
       - name: checkout git repo
         uses: actions/checkout@v3
         
       - name: login to docker
         uses: docker/login-action@v2
         with:
          username: ${{ secrets.docker_name_user }}
          password: ${{ secrets.DOCKERHUB }}
         
       #- name: build docker image
         #run:  docker build -t 10402033/hangmanmultistage:latest ${{ env.WORKING_DIR }}
       
       - name: Set up QEMU
         uses: docker/setup-buildx-action@v2
       
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
         
       - name: Build and push
         uses: docker/build-push-action@v4
         with:
          context: ${{ env.WORKING_DIR }}
          push: true
          tags: 10402033/templateapi:v2

       
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v2
         with:
          name: .net-app
          path: TemplateApi
          context: ${{ env.WORKING_DIR }}
          
      
          
  deploy:
    runs-on: ubuntu-latest
    needs: TemplateApiMulti
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:  
      - name: Set up Azure Web App Service
        id: setup-webapp
        uses: azure/webapps-setup@v1
        with:
          app-name: 'TemplateApi'
          sku: 'B1'
          # If you want to deploy to a specific region, uncomment and set the following parameter
          location: 'eastus'

   
      - name: Download artifact from buildMultistage job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
          context: ${{ env.WORKING_DIR }}
        
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TemplateApi'
          #context: ${{ env.WORKING_DIR }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.HANGMANAPI }}
          package: .
         
    
        
   

   
  
     
 
   
